import type {Metadata} from "next";
import "@/css/styles.css";
import {UserContextProvider} from "@/shared/context/UserContextProvider";
import "bootstrap/dist/css/bootstrap.min.css";
import Wrapper from "@/components/layout/Wrapper";
import NavBar from "@/components/layout/NavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {

    return (
        <>
            <html lang="en">
            <body>
            <UserContextProvider>
                <NavBar></NavBar>
                <Wrapper>
                    {children}
                </Wrapper>
            </UserContextProvider>
            </body>
            </html>
        </>
    );
}
