apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "medical-center-reception-frontend.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: medical-center-reception.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "medical-center-reception-frontend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
