import type { Metadata } from "next";
import "@/css/styles.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import { UserContextProvider } from "@/shared/context/UserContextProvider";
import Wrapper from "@/components/layout/Wrapper";
import NavBar from "@/components/layout/NavBar";
import ToastContainerInstance from "@/components/toast/ToastContainerInstance";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body>
          <ToastContainerInstance></ToastContainerInstance>
          <UserContextProvider>
            <NavBar></NavBar>
            <Wrapper>{children}</Wrapper>
          </UserContextProvider>
        </body>
      </html>
    </>
  );
}
