apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root2
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: default 
  source:
    path   : "k8s-deployment/argocd/apps"
    repoURL: 'https://github.com/otkisyan/medical-center-frontend.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
