import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/css/styles.css";
import {UserContextProvider} from "@/shared/context/UserContextProvider";

import "bootstrap/dist/css/bootstrap.min.css";
import Wrapper from "@/components/layout/Wrapper";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function UserLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {

    return (
        <>
            <html lang="en">
            <body className={inter.className}>
            <UserContextProvider>
                <Wrapper>
                    {children}
                </Wrapper>
            </UserContextProvider>
            </body>
            </html>
        </>
    );
}
